const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let signals=[],equity=[],research=[],industries=[],ratings=[],researchStocks=[],fundFlows=[],globalMarkets=[],cycles=[],tradeOps=[],evaluations=[],dataStatus={},analysisUniverse=new Map(),evaluationSort={key:'signal_at',direction:-1},currentView='overview',selectedSymbol=null,chatHistory=[],industryHits=[],stockHits=[];
const viewLoads=new Map();
const pct=v=>v==null?'—':`${(Number(v)*100).toFixed(2)}%`,num=(v,d=2)=>v==null?'—':Number(v).toFixed(d),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options){const r=await fetch(`/api/${path}`,{cache:'no-store',...options});if(!r.ok)throw Error(await r.text());return r.json()}
async function setAnalysisStatus(symbol,included,purchasePrice=null){await api('analysis-universe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,included,purchase_price:purchasePrice})});analysisUniverse.set(symbol,included);renderSignals()}
function badge(a){return a==='NO_SIGNAL'?'<span class="badge NO_SIGNAL">无信号</span>':a?`<span class="badge ${a}">${a}</span>`:''}
function setView(name){currentView=name;$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===name));updateChatContext();ensureViewData(name);requestAnimationFrame(drawVisibleCharts)}
function canvasContext(canvas){const dpr=devicePixelRatio||1,w=Math.max(canvas.clientWidth,300),h=+canvas.getAttribute('height');canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);c.font='10px Segoe UI,Microsoft YaHei,sans-serif';return{c,w,h}}
function drawAxes(c,w,h,m,xLabel,yLabel){c.strokeStyle='#365048';c.lineWidth=1;c.beginPath();c.moveTo(m.l,m.t);c.lineTo(m.l,h-m.b);c.lineTo(w-m.r,h-m.b);c.stroke();c.fillStyle='#789087';c.font='9px Segoe UI,Microsoft YaHei,sans-serif';c.textAlign='center';c.fillText(xLabel,(m.l+w-m.r)/2,h-6);c.save();c.translate(11,(m.t+h-m.b)/2);c.rotate(-Math.PI/2);c.fillText(yLabel,0,0);c.restore()}
function drawLine(canvas,data,key,{xKey='trade_date',xLabel='交易日期',yLabel='累计净值',formatY=v=>v.toFixed(2)}={}){if(!canvas||!data.length)return;const{c,w,h}=canvasContext(canvas),m={l:58,r:14,t:10,b:38},vals=data.map(x=>+x[key]).filter(Number.isFinite);if(!vals.length)return;let lo=Math.min(...vals),hi=Math.max(...vals),pad=(hi-lo||1)*.12;lo-=pad;hi+=pad;drawAxes(c,w,h,m,xLabel,yLabel);for(let i=0;i<4;i++){const y=m.t+(h-m.t-m.b)*i/3,v=hi-(hi-lo)*i/3;c.strokeStyle='#20332d';c.beginPath();c.moveTo(m.l,y);c.lineTo(w-m.r,y);c.stroke();c.fillStyle='#70857e';c.textAlign='right';c.fillText(formatY(v),m.l-7,y+3)}const ticks=[0,Math.floor((data.length-1)/3),Math.floor((data.length-1)*2/3),data.length-1];c.textAlign='center';ticks.forEach(i=>{const x=m.l+i/(data.length-1||1)*(w-m.l-m.r);c.fillStyle='#70857e';c.fillText(String(data[i][xKey]||'').slice(5,10),x,h-m.b+14)});const pts=data.map((d,i)=>[m.l+i/(data.length-1||1)*(w-m.l-m.r),m.t+(hi-(+d[key]))/(hi-lo)*(h-m.t-m.b)]);const grad=c.createLinearGradient(0,m.t,0,h-m.b);grad.addColorStop(0,'rgba(200,255,82,.22)');grad.addColorStop(1,'rgba(200,255,82,0)');c.beginPath();c.moveTo(pts[0][0],h-m.b);pts.forEach(p=>c.lineTo(...p));c.lineTo(pts.at(-1)[0],h-m.b);c.fillStyle=grad;c.fill();c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle='#c8ff52';c.lineWidth=2;c.stroke()}
function drawHorizontalBars(canvas,data){if(!canvas||!data.length)return;const rows=data.slice(0,10).reverse(),{c,w,h}=canvasContext(canvas),m={l:92,r:18,t:8,b:38},max=Math.max(...rows.map(x=>+x.sentiment_score),.1),plotW=w-m.l-m.r,rowH=(h-m.t-m.b)/rows.length;industryHits=[];drawAxes(c,w,h,m,'综合情绪评分（-1 至 1）','行业');for(let i=0;i<=4;i++){const x=m.l+plotW*i/4;c.strokeStyle='#20332d';c.beginPath();c.moveTo(x,m.t);c.lineTo(x,h-m.b);c.stroke();c.fillStyle='#70857e';c.textAlign='center';c.fillText((max*i/4).toFixed(2),x,h-m.b+14)}rows.forEach((r,i)=>{const y=m.t+i*rowH+rowH*.18,bh=rowH*.62,bw=Math.max(2,(+r.sentiment_score/max)*plotW);c.fillStyle='rgba(96,230,168,.72)';c.fillRect(m.l,y,bw,bh);c.fillStyle='#9aaca6';c.textAlign='right';c.fillText(String(r.industry_name).slice(0,8),m.l-7,y+bh*.72);c.fillStyle='#dfe9e5';c.textAlign='left';c.fillText((+r.sentiment_score).toFixed(2),Math.min(m.l+bw+5,w-32),y+bh*.72);industryHits.push({x:0,y:y-rowH*.18,w,h:rowH,industry:r.industry_name})})}
function drawVerticalBars(canvas,data){if(!canvas||!data.length)return;const rows=data.filter(x=>Number.isFinite(+x.research_score)).slice(0,8),{c,w,h}=canvasContext(canvas),m={l:48,r:12,t:8,b:62},max=Math.max(...rows.map(x=>+x.research_score),.1),plotH=h-m.t-m.b,plotW=w-m.l-m.r;stockHits=[];drawAxes(c,w,h,m,'研报映射候选股票','行业研报综合评分');const slot=plotW/Math.max(rows.length,1);rows.forEach((r,i)=>{const bh=Math.max(2,(+r.research_score/max)*plotH),x=m.l+i*slot+slot*.16,y=h-m.b-bh,bw=slot*.68;c.fillStyle=r.quant_action==='BUY'?'#60e6a8':r.quant_action==='SELL'?'#ff7e75':'#f3c968';c.fillRect(x,y,bw,bh);c.fillStyle='#8fa19b';c.textAlign='center';c.save();c.translate(x+bw/2,h-m.b+12);c.rotate(-.55);c.fillText(`${r.symbol} ${String(r.name).slice(0,4)}`,0,0);c.restore();c.fillStyle='#e5eeeb';c.fillText((+r.research_score).toFixed(2),x+bw/2,y-4);stockHits.push({x,y,w:bw,h:bh,symbol:r.symbol})})}
function drawVisibleCharts(){if(currentView==='overview')drawLine($('#equity-chart'),equity,'equity');if(currentView==='performance')drawLine($('#equity-chart-large'),equity,'equity');if(currentView==='research'){drawHorizontalBars($('#industry-chart'),industries);drawVerticalBars($('#rating-chart'),researchStocks)}}
function renderSignals(){const q=$('#signal-search').value.trim().toLowerCase(),f=$('#signal-filter').value;$('#signals-body').innerHTML=signals.filter(s=>(f==='ALL'||s.action===f)&&`${s.symbol} ${s.name} ${s.industry}`.toLowerCase().includes(q)).map(s=>`<tr data-symbol="${s.symbol}"><td>#${s.hot_rank}</td><td><strong>${s.symbol}</strong><br><small class="muted">${esc(s.name)}</small></td><td>${esc(s.industry||'—')}</td><td>${badge(s.action)}</td><td>${pct(s.probability)}</td><td>${pct(s.confidence)}</td><td>${num(s.current_price)}</td><td class="${+s.pct_change>=0?'positive':'negative'}">${s.pct_change==null?'—':num(s.pct_change)+'%'}</td><td>${s.signal_at||s.price_date}</td><td><button class="row-action" data-remove="${s.symbol}">移除分析</button></td></tr>`).join('');$$('#signals-body tr').forEach(r=>r.onclick=()=>showSymbol(r.dataset.symbol));$$('[data-remove]').forEach(b=>b.onclick=async e=>{e.stopPropagation();await setAnalysisStatus(b.dataset.remove,false)})}
function renderResearch(){const q=$('#research-search').value.trim().toLowerCase(),f=$('#research-filter').value;$('#research-body').innerHTML=research.filter(r=>(f==='ALL'||r.stance===f)&&`${r.title} ${r.industry_name} ${r.broker_name}`.toLowerCase().includes(q)).map(r=>`<tr><td>${r.publish_date}</td><td>${esc(r.industry_name)}</td><td>${esc(r.broker_name)}</td><td>${esc(r.rating||'未评级')}</td><td><span class="stance ${r.stance}">${r.stance}</span></td><td>${num(r.sentiment_score)}</td><td class="title-cell"><a href="${esc(r.source_url)}" target="_blank" rel="noopener">${esc(r.title)}</a></td><td class="summary-cell">${esc(r.summary)}</td></tr>`).join('')}
function renderResearchStocks(){const rows=researchStocks.filter(x=>+x.research_score>=.3);$('#research-stocks-body').innerHTML=rows.length?rows.map(x=>`<tr data-symbol="${x.symbol}"><td><strong>${x.symbol}</strong><br><small class="muted">${esc(x.name)}</small></td><td>${esc(x.industry)}</td><td>${x.in_analysis_list?'<span class="badge BUY">自选股票所属行业</span>':'—'}</td><td><span class="stance ${x.research_stance}">${x.research_stance}</span></td><td>${num(x.research_score)}</td><td>${x.related_reports} 篇</td><td>${x.broker_count} 家</td><td>${esc(x.ratings||'未评级')}</td><td>${badge(x.quant_action)} ${pct(x.probability)}</td></tr>`).join(''):`<tr><td colspan="9" class="muted">最新研报行业与当前热榜股票暂未形成偏多映射。</td></tr>`;$$('#research-stocks-body tr[data-symbol]').forEach(r=>r.onclick=()=>showSymbol(r.dataset.symbol))}
async function showSymbol(symbol){selectedSymbol=symbol;updateChatContext();$('#symbol-dialog').showModal();$('#symbol-detail').innerHTML='<p class="muted">正在加载30日综合分析…</p>';try{const d=await api(`stock-analysis?symbol=${symbol}`);$('#symbol-detail').innerHTML=`<p class="eyebrow">30-DAY STOCK ANALYSIS</p><div class="detail-title"><div><h2>${symbol} · ${esc(d.name||symbol)}</h2><p>${esc(d.industry||'行业待补充')} · 日线数据至 ${d.as_of}</p></div>${badge(d.action)}</div><div class="analysis-kpis"><span>综合分<strong>${num(d.score,1)}</strong></span><span>置信度<strong>${pct(d.confidence)}</strong></span><span>30日收益<strong class="${d.return_30d>=0?'positive':'negative'}">${pct(d.return_30d)}</strong></span><span>RSI(14)<strong>${num(d.rsi14,1)}</strong></span><span>最大回撤<strong>${pct(d.max_drawdown_30d)}</strong></span></div><div class="analysis-columns"><div><h3>主要依据</h3><ul>${d.reasons.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>暂无强支持项</li>'}</ul></div><div><h3>风险与限制</h3><ul>${d.risks.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>未触发额外风险项</li>'}</ul></div></div><p class="analysis-note">${esc(d.method)}。${esc(d.disclaimer)}</p>`;const intra=d.intraday?.points||[];if(intra.length)drawLine($('#symbol-chart'),intra,'price',{xKey:'time',xLabel:d.intraday.trade_date,yLabel:'分钟价格（元）'});else drawLine($('#symbol-chart'),d.bars,'close',{xLabel:'交易日期',yLabel:'复权收盘价（元）'});$('#symbol-history').textContent=intra.length?`${d.intraday.market_state==='REALTIME'?'当日实时分钟走势':'非交易日/休市，显示最近交易日分钟全景'}：${d.intraday.trade_date}；30日综合分析仍基于复权日线。`:`分钟行情不可用，已展示近30个交易日全景。数据源：${d.data_source}`;}catch(e){$('#symbol-detail').innerHTML=`<h2>${symbol}</h2><p class="negative">分析失败：${esc(e.message)}</p>`}}
async function analyzeCode(symbol){const box=$('#stock-analysis-result');box.className='analysis-result muted';box.textContent='正在读取行情并计算…';try{const d=await api(`stock-analysis?symbol=${symbol}`);box.className=`analysis-result decision-${d.action}`;box.innerHTML=`<div><strong>${d.symbol} ${esc(d.name||'')} ${badge(d.action)}</strong><span>综合分 ${num(d.score,1)} · 置信度 ${pct(d.confidence)} · 30日收益 ${pct(d.return_30d)}</span></div><button type="button">查看完整走势与依据</button>`;box.querySelector('button').onclick=()=>showSymbol(d.symbol)}catch(e){box.className='analysis-result negative';box.textContent=`无法分析：${e.message}`}}
function renderOperations(){const statusMissing=!globalMarkets.length&&!cycles.length&&!tradeOps.length&&!fundFlows.length;$('#global-market-body').innerHTML=globalMarkets.length?globalMarkets.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.category)}</td><td>${esc(x.country||'—')}</td><td>${num(x.price)}</td><td class="${+x.change_pct>=0?'positive':'negative'}">${x.change_pct==null?'—':num(x.change_pct)+'%'}</td><td>${x.market_state==='OPEN'?'交易中':'最近收盘'}</td><td>${x.observed_at||'—'}</td></tr>`).join(''):`<tr><td colspan="7" class="empty-state">暂无全球市场快照。请显式运行 <code>main.py macro</code> 采集；Web 服务不会自动写库。</td></tr>`;$('#cycle-grid').innerHTML=cycles.length?cycles.map(x=>`<div class="digest-card"><div><strong>${esc(x.model_name)}</strong><span>${esc(x.phase)}</span></div><p>评分 ${num(x.score)} · 置信度 ${pct(x.confidence)}</p></div>`).join(''):`<div class="empty-state">暂无周期数据；运行 macro 后显示。</div>`;$('#trade-body').innerHTML=tradeOps.length?tradeOps.map(x=>`<tr><td>${esc(x.hs_name)}</td><td>${x.flow_code==='X'?'出口':'进口'}</td><td>${Number(x.latest_value_usd||0).toLocaleString()}</td><td>${pct(x.yoy_growth)}</td><td>${num(x.opportunity_score)}</td><td>${esc(Array.isArray(x.beneficiary_industries)?x.beneficiary_industries.join('、'):x.beneficiary_industries)}</td><td class="summary-cell">${esc(x.risk_note)}</td></tr>`).join(''):`<tr><td colspan="7" class="empty-state">暂无贸易结构数据；运行 macro 后显示。</td></tr>`;$('#fund-flow-body').innerHTML=fundFlows.length?fundFlows.map(x=>`<tr data-symbol="${x.symbol}"><td>${x.symbol} ${esc(x.name)}</td><td>${num(x.follow_score)}</td><td>${pct(x.reliability)}</td><td>${esc(x.recommendation)}</td><td>${x.quant_action?badge(x.quant_action):'—'}</td><td>${esc(JSON.stringify(x.factors||{}))}</td></tr>`).join(''):`<tr><td colspan="6" class="empty-state">暂无资金流快照。数据状态：${dataStatus.fund_flow_rows||0} 条；运行 <code>main.py macro</code> 后显示。</td></tr>`;$$('#fund-flow-body tr[data-symbol]').forEach(r=>r.onclick=()=>showSymbol(r.dataset.symbol));if(statusMissing)$('#market-status').title='宏观与资金流尚未采集；核心数据库连接正常'}
function renderEvaluations(summary){$('#evaluation-summary').textContent=summary.evaluated_count?`已完成五日验收 ${summary.evaluated_count} 条 · 准确率 ${summary.median_accuracy||'—'}%`:'等待第 5 个后续交易日行情';const sorted=[...evaluations].sort((a,b)=>{let x=a[evaluationSort.key],y=b[evaluationSort.key];if(typeof x==='number'||typeof y==='number'){x=Number(x??-Infinity);y=Number(y??-Infinity)}return(x>y?1:x<y?-1:0)*evaluationSort.direction});$('#evaluation-body').innerHTML=sorted.length?sorted.map(x=>`<tr data-symbol="${x.symbol}"><td>${x.signal_at}</td><td>${x.evaluation_date||`观察中（${Math.min(x.trading_days_elapsed,4)}/5）`}</td><td>${x.symbol} ${esc(x.name)}</td><td>${pct(x.confidence)}</td><td>${x.raw_action?badge(x.raw_action):''}</td><td>${x.execution_action?badge(x.execution_action):''}</td><td class="${x.median_return==null?'':+x.median_return>=0?'positive':'negative'}">${x.median_return==null?'':pct(x.median_return)}</td><td>${x.direction_correct==null?'':x.direction_correct?'是':'否'}</td></tr>`).join(''):`<tr><td colspan="8" class="empty-state">暂无置信度达到 60% 的历史信号。</td></tr>`;const mature=sorted.filter(x=>x.evaluation_date);$('#performance-evaluation-body').innerHTML=mature.length?mature.map(x=>`<tr data-symbol="${x.symbol}"><td>${x.signal_date} / ${x.evaluation_date}</td><td>${x.symbol} ${esc(x.name)}</td><td>${badge(x.signal_action)}</td><td>${num(x.signal_median_price)}</td><td>${num(x.evaluation_median_price)}</td><td class="${+x.median_return>=0?'positive':'negative'}">${pct(x.median_return)}</td><td>${x.median_correct?'正确':'错误'}</td><td>第5个交易日验收</td></tr>`).join(''):`<tr><td colspan="8" class="empty-state">暂无完成五日观察期的信号。</td></tr>`;$$('#evaluation-body tr[data-symbol],#performance-evaluation-body tr[data-symbol]').forEach(r=>r.onclick=()=>showSymbol(r.dataset.symbol))}
function renderCore(s,runs,weights,q,changes){$('#run-time').textContent=s.created_at||'—';$('#run-id').textContent=s.run_id||'—';$('#annual-return').textContent=pct(s.annual_return);$('#sharpe').textContent=num(s.sharpe);$('#drawdown').textContent=pct(s.max_drawdown);$('#accuracy').textContent=pct(s.direction_accuracy);$('#baseline').textContent=`基线 ${pct(s.baseline_accuracy)}`;['buy','hold','sell'].forEach(x=>$(`#${x}-count`).textContent=s[`${x}_count`]??0);$('#total-signals').textContent=signals.length;$('#latest-date').textContent=`数据至 ${s.latest_date||'—'}`;$('#donut').style.setProperty('--buy-p',`${(s.buy_count/(signals.length||1))*100}%`);$('#donut').style.setProperty('--hold-p',`${(s.hold_count/(signals.length||1))*100}%`);$('#signal-cards').innerHTML=signals.filter(x=>x.action==='BUY').slice(0,5).map(x=>`<div class="signal-card" data-symbol="${x.symbol}"><div class="row"><strong>${x.symbol}</strong>${badge(x.action)}</div><div class="stock-name">${esc(x.name)}</div><div class="stock-industry">${esc(x.industry||'—')}</div><div class="prob">${pct(x.probability)}</div><small class="muted">热度 #${x.hot_rank} · 置信 ${pct(x.confidence)}</small></div>`).join('');$$('.signal-card').forEach(x=>x.onclick=()=>showSymbol(x.dataset.symbol));renderSignals();$('#runs-body').innerHTML=runs.map(r=>`<tr><td>${r.created_at}</td><td>${num(r.threshold)}</td><td>${r.top_k}</td><td>${pct(r.annual_return)}</td><td>${num(r.sharpe)}</td><td>${pct(r.max_drawdown)}</td><td>${pct(r.accuracy)}</td></tr>`).join('');const mw=Math.max(...weights.map(x=>Math.abs(x.coefficient)),1);$('#weights').innerHTML=weights.map(w=>`<div class="weight-row"><span>${w.feature_name}</span><div class="weight-track"><div class="weight-bar ${w.coefficient<0?'neg':''}" style="width:${Math.abs(w.coefficient)/mw*100}%"></div></div><strong>${num(w.coefficient,3)}</strong></div>`).join('');$('#quality-grid').innerHTML=[['历史行情',`${Number(q.bar_count||s.bar_count||0).toLocaleString()} 条`,`覆盖 ${q.symbol_count||0} 只股票`],['数据区间',q.database_earliest||'—',`至 ${q.database_latest||'—'}`],['陈旧股票',`${q.stale_symbol_count??'—'} 只`,`下载错误 ${q.download_error_count??'—'} 个`],['热榜快照',Number(q.universe_snapshot_rows||0).toLocaleString(),'持续积累 point-in-time'],['信号历史',Number(q.signal_rows||0).toLocaleString(),'可审计决策记录'],['模型运行',`${q.model_run_rows||0} 次`,q.checked_local||'—']].map(x=>`<div class="quality-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');$('#changes-body').innerHTML=changes.map(c=>`<tr><td>${c.changed_at}</td><td>${c.symbol}</td><td>${c.previous_action||'—'}</td><td>${c.current_action||'—'}</td><td>${pct(c.previous_probability)}</td><td>${pct(c.current_probability)}</td><td>${c.change_type}</td></tr>`).join('')}
function jumpIndustryReports(industry){$('#research-search').value=industry;renderResearch();$('#research-body').closest('.panel').scrollIntoView({behavior:'smooth',block:'start'})}
function jumpIndustryStock(industry){const stock=researchStocks.find(x=>x.industry===industry);if(stock)showSymbol(stock.symbol);else jumpIndustryReports(industry)}
function renderResearchPanel(rs,digests){$('#research-time').textContent=`最近抓取 ${rs.last_ingestion||'—'}`;$('#research-kpis').innerHTML=[['最新研报',`${rs.report_count||0} 篇`,rs.latest_date||'—'],['覆盖券商',`${rs.broker_count||0} 家`,'公开聚合源'],['覆盖行业',`${rs.industry_count||0} 个`,'按行业形成共识'],['偏多占比',`${rs.bullish_ratio||0}%`,'规则分析，可审计']].map(x=>`<article class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');$('#digest-grid').innerHTML=digests.slice(0,8).map(x=>`<button class="digest-card digest-button" data-industry="${esc(x.industry_name)}"><div><strong>${esc(x.industry_name)}</strong><span class="stance ${x.stance}">${x.stance}</span></div><p>${esc(x.summary)}</p><small>${x.report_count} 篇 · ${x.broker_count} 家券商 · 评分 ${num(x.sentiment_score)} · 点击查看行业股票走势</small></button>`).join('');$$('.digest-button').forEach(x=>x.onclick=()=>jumpIndustryStock(x.dataset.industry));renderResearch();renderResearchStocks()}
function updateChatContext(){const stock=signals.find(x=>x.symbol===selectedSymbol);$('#chat-context').textContent=`当前上下文：${({overview:'总览',signals:'股票信号',funds:'资金流',macro:'全球宏观',performance:'回测',research:'行业研报',quality:'数据质量'})[currentView]}${stock?` · ${stock.symbol} ${stock.name}`:''}`}
function addChat(role,text,extra=''){const div=document.createElement('div');div.className=`chat-message ${role} ${extra}`;div.textContent=text;$('#chat-messages').append(div);$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;return div}
async function sendChat(message){message=message.trim();if(!message)return;addChat('user',message);$('#chat-input').value='';const loading=addChat('assistant','正在读取当前指标并分析…','loading');try{const context={view:currentView,selected_symbol:selectedSymbol};const result=await api('chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,history:chatHistory.slice(-6),context})});loading.remove();addChat('assistant',result.answer);chatHistory.push({role:'user',content:message},{role:'assistant',content:result.answer})}catch(e){loading.textContent='对话服务暂时不可用，请稍后重试。';console.error(e)}}
async function ensureViewData(name){
  const group=name==='research'?'research':['funds','macro'].includes(name)?'operations':['performance','quality'].includes(name)?'evaluations':null;
  if(!group||viewLoads.has(group))return viewLoads.get(group);
  const job=(async()=>{
    if(group==='research'){
      const d=await Promise.all(['research-summary','research-digests','research-reports','research-industries','research-ratings','research-stocks'].map(api));
      research=d[2];industries=d[3];ratings=d[4];researchStocks=d[5];renderResearchPanel(d[0][0]||{},d[1]);
    }else if(group==='operations'){
      const d=await Promise.all(['fund-flows','global-markets','cycles','trade-opportunities','data-status'].map(api));
      fundFlows=d[0];globalMarkets=d[1];cycles=d[2];tradeOps=d[3];dataStatus=d[4][0]||{};renderOperations();
    }else{
      const d=await Promise.all(['evaluation-summary','evaluations'].map(api));
      evaluations=d[1];renderEvaluations(d[0][0]||{});
    }
    requestAnimationFrame(drawVisibleCharts);
  })().catch(e=>{viewLoads.delete(group);console.error(e);$('#market-status').textContent='部分数据加载失败'});
  viewLoads.set(group,job);return job;
}
async function load(){try{const d=await Promise.all(['summary','signals','equity','runs','weights','quality','changes'].map(api));signals=d[1];equity=d[2];renderCore(d[0][0]||{},d[3],d[4],d[5][0]||{},d[6]);requestAnimationFrame(drawVisibleCharts);$('#market-status').textContent='数据已连接'}catch(e){console.error(e);$('#market-status').textContent='连接异常'}}
$$('.nav-btn').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-goto]').forEach(b=>b.onclick=()=>setView(b.dataset.goto));$$('[data-filter]').forEach(b=>b.onclick=()=>{setView('signals');$('#signal-filter').value=b.dataset.filter;renderSignals()});$('#signal-search').oninput=renderSignals;$('#signal-filter').onchange=renderSignals;$('#research-search').oninput=renderResearch;$('#research-filter').onchange=renderResearch;$('#stock-analysis-form').onsubmit=e=>{e.preventDefault();analyzeCode($('#stock-analysis-code').value.trim())};$('#industry-chart').onclick=e=>{const r=e.target.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,hit=industryHits.find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h);if(hit)jumpIndustryReports(hit.industry)};$('#rating-chart').onclick=e=>{const r=e.target.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,hit=stockHits.find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h);if(hit)showSymbol(hit.symbol)};$('.dialog-close').onclick=()=>{$('#symbol-dialog').close();selectedSymbol=null;updateChatContext()};$('#chat-launcher').onclick=()=>{$('#chat-panel').classList.add('open');$('#chat-launcher').hidden=true};$('#chat-close').onclick=()=>{$('#chat-panel').classList.remove('open');$('#chat-launcher').hidden=false};$('#chat-form').onsubmit=e=>{e.preventDefault();sendChat($('#chat-input').value)};$('.chat-suggestions').onclick=e=>{if(e.target.tagName==='BUTTON')sendChat(e.target.textContent)};setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false}),1000);addEventListener('resize',()=>requestAnimationFrame(drawVisibleCharts));updateChatContext();load();setInterval(load,60000);
