(function(){
'use strict';
const S={symbol:'601899',bars:[],type:'candles',period:'1D',indicator:'VOL',tool:'cursor',scale:1,offset:0,cross:null,drawings:[],draft:null};
const q=s=>document.querySelector(s), el=(tag,cls,html='')=>{const n=document.createElement(tag);n.className=cls;n.innerHTML=html;return n};
function icon(label,title,tool=''){return `<button class="tv-icon" title="${title}" aria-label="${title}" ${tool?`data-tool="${tool}"`:''}>${label}</button>`}
function build(){
 document.body.classList.add('tv-mode'); const shell=q('.shell'), main=q('main'), top=q('.topbar');
 top.insertAdjacentHTML('afterend',`<div class="tv-command"><button class="tv-symbol"><b id="tv-symbol">${S.symbol}</b><span id="tv-symbol-name">选择股票</span></button><button class="tv-period active">日</button><button class="tv-period">周</button><button class="tv-period">月</button><i></i><button id="tv-type">蜡烛图⌄</button><button id="tv-indicator">指标</button><button>预警</button><button>回放</button><span class="tv-command-spacer"></span><button>撤销</button><button>重做</button><button>布局</button><button>保存</button><button>设置</button><button id="tv-fullscreen">全屏</button><button>截图</button></div>`);
 const stage=el('div','tv-stage'); const rail=el('aside','tv-left',`${icon('＋','十字光标','cursor')}${icon('╱','趋势线','trend')}${icon('—','水平线','horizontal')}${icon('▱','矩形','rect')}${icon('F','斐波那契回撤','fib')}${icon('T','文字','text')}<span></span>${icon('⌕','放大')}${icon('⊙','磁铁模式')}${icon('🔒','锁定绘图')}${icon('⌫','删除全部绘图','clear')}`);
 const center=el('div','tv-center'); const right=el('aside','tv-right',`<div class="tv-side-tabs"><button class="active">自选</button><button>详情</button><button>新闻</button></div><div class="tv-watch-head"><b>我的自选</b><button title="添加股票">＋</button></div><div class="tv-watch-cols"><span>代码</span><span>最新</span><span>涨幅</span></div><div id="tv-watch" class="tv-watch"></div><div id="tv-quote" class="tv-quote"><p>选择股票查看行情详情</p></div>`);
 shell.insertBefore(stage,main); stage.append(rail,center,right); center.append(main);
 const chart=el('section','tv-chart-panel',`<div class="tv-chart-title"><div><b id="tv-chart-name">${S.symbol}</b><span id="tv-chart-market">A股 · 1日</span></div><div class="tv-ohlc" id="tv-ohlc">O — H — L — C —</div></div><canvas id="tv-main-chart" aria-label="专业K线图"></canvas><div class="tv-chart-status"><span id="tv-chart-status">正在读取行情…</span><span class="tv-range"><button>1日</button><button>5日</button><button>1月</button><button>3月</button><button>6月</button><button>年初至今</button><button>1年</button><button>全部</button></span><span>Asia/Shanghai</span><span>复权</span></div>`);
 main.insertBefore(chart,main.firstChild);
 center.insertAdjacentHTML('beforeend',`<div class="tv-bottom"><div class="tv-bottom-tabs"><button data-bottom="signals">股票筛选器</button><button data-bottom="performance">策略测试器</button><button data-bottom="news">新闻影响</button><button data-bottom="quality">模型审计</button><button data-bottom="research">研报</button><button>交易面板</button><span></span><button id="tv-collapse">⌃</button></div></div>`);
 bind(); loadPinnedWatch();
}
async function loadPinnedWatch(){try{const [signals,watchlist]=await Promise.all([fetch('/api/signals',{cache:'no-store'}).then(r=>r.json()),fetch('/api/analysis-universe',{cache:'no-store'}).then(r=>r.json())]);const fixed=watchlist.map(x=>({...x,_watch_group:'fixed',pct_change:x.holding_return==null?null:x.holding_return*100,name:`${x.name||x.symbol} · 成本 ${x.purchase_price==null?'待补':Number(x.purchase_price).toFixed(3)}`}));const list=[...fixed,...signals.map(x=>({...x,_watch_group:'hot'}))];syncWatch(list);loadChart(list[0]?.symbol||S.symbol)}catch(e){q('#tv-chart-status').textContent='自选列表连接异常';loadChart(S.symbol)}}
async function waitForData(){try{const list=await fetch('/api/signals',{cache:'no-store'}).then(r=>r.json());syncWatch(list);loadChart(list[0]?.symbol||S.symbol)}catch(e){q('#tv-chart-status').textContent='行情列表连接异常';loadChart(S.symbol)}}
function bind(){
 q('.tv-left').onclick=e=>{const b=e.target.closest('[data-tool]');if(!b)return; if(b.dataset.tool==='clear'){S.drawings=[];draw();return} S.tool=b.dataset.tool;q('.tv-left .active')?.classList.remove('active');b.classList.add('active')};
 q('.tv-command').onclick=e=>{if(e.target.id==='tv-fullscreen')document.documentElement.requestFullscreen?.();if(e.target.id==='tv-type'){S.type=S.type==='candles'?'line':S.type==='line'?'area':'candles';e.target.textContent={candles:'蜡烛图⌄',line:'折线图⌄',area:'面积图⌄'}[S.type];draw()}if(e.target.id==='tv-indicator'){S.indicator=S.indicator==='VOL'?'MA':'VOL';e.target.textContent=S.indicator==='MA'?'指标 · MA20':'指标';draw()}};
 q('.tv-bottom-tabs').onclick=e=>{const v=e.target.dataset.bottom;if(v&&window.setView)window.setView(v)};
 q('#tv-symbol').parentElement.onclick=()=>{const code=prompt('输入6位A股代码',S.symbol);if(/^\d{6}$/.test(code||''))loadChart(code)};
 const c=q('#tv-main-chart'); c.addEventListener('mousemove',e=>{S.cross={x:e.offsetX,y:e.offsetY};if(S.draft){S.draft.x2=e.offsetX;S.draft.y2=e.offsetY}draw()});c.addEventListener('mouseleave',()=>{S.cross=null;draw()});c.addEventListener('wheel',e=>{if(!(e.ctrlKey||e.metaKey))return;e.preventDefault();S.scale=Math.max(.5,Math.min(5,S.scale*(e.deltaY<0?1.12:.9)));draw()},{passive:false});
 c.addEventListener('mousedown',e=>{if(S.tool==='cursor')return;S.draft={tool:S.tool,x1:e.offsetX,y1:e.offsetY,x2:e.offsetX,y2:e.offsetY}});c.addEventListener('mouseup',()=>{if(S.draft){S.drawings.push(S.draft);S.draft=null;draw()}});
 addEventListener('resize',draw);
}
async function loadChart(symbol){S.symbol=symbol;q('#tv-symbol').textContent=symbol;q('#tv-chart-status').textContent='正在读取行情…';try{const d=await fetch(`/api/stock-analysis?symbol=${symbol}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('行情不可用');return r.json()});S.bars=d.bars||[];q('#tv-symbol-name').textContent=d.name||symbol;q('#tv-chart-name').textContent=`${symbol} · ${d.name||''}`;q('#tv-chart-market').textContent=`${d.industry||'A股'} · 1日 · ${d.as_of||''}`;q('#tv-chart-status').textContent=`${S.bars.length}根K线 · ${d.data_source||'行情数据'}`;renderQuote(d);draw()}catch(e){q('#tv-chart-status').textContent=e.message}}
function syncWatch(source=[]){const list=source.slice(0,30);q('#tv-watch').innerHTML=list.map(x=>`<button data-symbol="${x.symbol}"><span><b>${x.symbol}</b><small>${x.name||''}</small></span><span>${Number(x.current_price||0).toFixed(2)}</span><span class="${Number(x.pct_change)>=0?'up':'down'}">${Number(x.pct_change||0).toFixed(2)}%</span></button>`).join('');q('#tv-watch').onclick=e=>{const b=e.target.closest('[data-symbol]');if(b)loadChart(b.dataset.symbol)}}
function renderQuote(d){const b=S.bars.at(-1)||{};q('#tv-quote').innerHTML=`<h3>${S.symbol}</h3><h2>${d.name||''}</h2><strong>${Number(b.close||0).toFixed(2)}</strong><p>${d.industry||'—'} · ${d.action||'HOLD'} · 置信度 ${(Number(d.confidence||0)*100).toFixed(2)}%</p><div><span>30日收益</span><b>${(Number(d.return_30d||0)*100).toFixed(2)}%</b></div><div><span>RSI(14)</span><b>${Number(d.rsi14||0).toFixed(1)}</b></div>`}
function draw(){const c=q('#tv-main-chart');if(!c||!S.bars.length)return;const dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);const m={l:10,r:72,t:18,b:42},bars=S.bars.slice(-Math.max(10,Math.round(90/S.scale))),lo=Math.min(...bars.map(b=>+b.low)),hi=Math.max(...bars.map(b=>+b.high)),pw=w-m.l-m.r,ph=h-m.t-m.b,xx=i=>m.l+(i+.5)*pw/bars.length,yy=v=>m.t+(hi-v)/(hi-lo||1)*ph;
 x.strokeStyle='#252a35';x.lineWidth=1;for(let i=0;i<7;i++){let y=m.t+i*ph/6;x.beginPath();x.moveTo(m.l,y);x.lineTo(w-m.r,y);x.stroke();x.fillStyle='#8b8e99';x.textAlign='left';x.font='11px Segoe UI';x.fillText((hi-(hi-lo)*i/6).toFixed(2),w-m.r+8,y+4)}for(let i=0;i<6;i++){let z=m.l+i*pw/5;x.beginPath();x.moveTo(z,m.t);x.lineTo(z,h-m.b);x.stroke()}
 const bw=Math.max(2,pw/bars.length*.64);if(S.type==='candles')bars.forEach((b,i)=>{const up=+b.close>=+b.open,col=up?'#26a69a':'#ef5350',cx=xx(i);x.strokeStyle=x.fillStyle=col;x.beginPath();x.moveTo(cx,yy(+b.high));x.lineTo(cx,yy(+b.low));x.stroke();x.fillRect(cx-bw/2,Math.min(yy(+b.open),yy(+b.close)),bw,Math.max(1,Math.abs(yy(+b.open)-yy(+b.close))))});else{const pts=bars.map((b,i)=>[xx(i),yy(+b.close)]);if(S.type==='area'){const g=x.createLinearGradient(0,m.t,0,h-m.b);g.addColorStop(0,'rgba(41,98,255,.36)');g.addColorStop(1,'rgba(41,98,255,0)');x.beginPath();x.moveTo(pts[0][0],h-m.b);pts.forEach(p=>x.lineTo(...p));x.lineTo(pts.at(-1)[0],h-m.b);x.fillStyle=g;x.fill()}x.beginPath();pts.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.strokeStyle='#2962ff';x.lineWidth=2;x.stroke()}
 if(S.indicator==='MA'&&bars.length>3){x.beginPath();bars.forEach((b,i)=>{const a=bars.slice(Math.max(0,i-19),i+1),v=a.reduce((s,z)=>s+ +z.close,0)/a.length;i?x.lineTo(xx(i),yy(v)):x.moveTo(xx(i),yy(v))});x.strokeStyle='#f5a623';x.lineWidth=1.5;x.stroke()}
 const all=[...S.drawings,...(S.draft?[S.draft]:[])];x.strokeStyle='#7c4dff';x.fillStyle='rgba(124,77,255,.12)';x.lineWidth=1.5;all.forEach(a=>{x.beginPath();if(a.tool==='horizontal'){x.moveTo(m.l,a.y1);x.lineTo(w-m.r,a.y1)}else if(a.tool==='rect'){x.rect(a.x1,a.y1,a.x2-a.x1,a.y2-a.y1);x.fill()}else{x.moveTo(a.x1,a.y1);x.lineTo(a.x2,a.y2)}x.stroke()});
 if(S.cross){x.setLineDash([4,4]);x.strokeStyle='#777b87';x.beginPath();x.moveTo(S.cross.x,m.t);x.lineTo(S.cross.x,h-m.b);x.moveTo(m.l,S.cross.y);x.lineTo(w-m.r,S.cross.y);x.stroke();x.setLineDash([]);const i=Math.max(0,Math.min(bars.length-1,Math.floor((S.cross.x-m.l)/pw*bars.length))),b=bars[i];if(b)q('#tv-ohlc').textContent=`O ${b.open}  H ${b.high}  L ${b.low}  C ${b.close}`}
 bars.filter((_,i)=>i%Math.max(1,Math.floor(bars.length/5))===0).forEach((b,i,a)=>{const bi=bars.indexOf(b);x.fillStyle='#8b8e99';x.textAlign='center';x.fillText(String(b.trade_date||'').slice(5),xx(bi),h-17)})
}
const baseRenderQuote=renderQuote;
renderQuote=function(d){baseRenderQuote(d);const i=d.indicators||{},p=d.position_analysis,box=q('#tv-quote');if(p)box.insertAdjacentHTML('beforeend',`<section class="tv-position"><h3>持仓分析 · ${p.action}</h3><div><span>购入价 / 现价</span><b>${Number(p.purchase_price).toFixed(3)} / ${Number(p.current_price).toFixed(2)}</b></div><div><span>持仓收益</span><b class="${p.holding_return>=0?'up':'down'}">${(p.holding_return*100).toFixed(2)}%</b></div><div><span>技术分 / 持仓分</span><b>${Number(p.technical_score).toFixed(1)} / ${Number(p.position_score).toFixed(1)}</b></div></section>`);box.insertAdjacentHTML('beforeend',`<div><span>MA5 / MA20 / MA60</span><b>${Number(i.sma5||0).toFixed(2)} / ${Number(i.sma20||0).toFixed(2)} / ${i.sma60==null?'—':Number(i.sma60).toFixed(2)}</b></div><div><span>MACD / Signal / Hist</span><b>${Number(i.macd||0).toFixed(3)} / ${Number(i.macd_signal||0).toFixed(3)} / ${Number(i.macd_histogram||0).toFixed(3)}</b></div><div><span>BOLL 上 / 中 / 下</span><b>${Number(i.bollinger_upper||0).toFixed(2)} / ${Number(i.bollinger_middle||0).toFixed(2)} / ${Number(i.bollinger_lower||0).toFixed(2)}</b></div><div><span>K / D / J</span><b>${Number(i.kdj_k||0).toFixed(1)} / ${Number(i.kdj_d||0).toFixed(1)} / ${Number(i.kdj_j||0).toFixed(1)}</b></div><div><span>ATR(14) / 量比</span><b>${Number(i.atr14||0).toFixed(2)} / ${Number(i.volume_ratio_5_20||0).toFixed(2)}</b></div>`)};
const baseSyncWatch=syncWatch;
syncWatch=function(source=[]){const fixed=source.filter(x=>x._watch_group==='fixed'),hot=source.filter(x=>x._watch_group!=='fixed');const row=x=>`<button data-symbol="${x.symbol}"><span><b>${x.symbol}</b><small>${x.name||''}</small></span><span>${Number(x.current_price||0).toFixed(2)}</span><span class="${Number(x.pct_change)>=0?'up':'down'}">${x.pct_change==null?'—':Number(x.pct_change).toFixed(2)+'%'}</span></button>`;q('#tv-watch').innerHTML=`<div class="tv-watch-group">我的固定自选 <em>${fixed.length}</em></div>${fixed.length?fixed.map(row).join(''):'<p class="tv-watch-empty">暂无固定自选</p>'}<div class="tv-watch-group hot">每日热度前十 <em>${hot.length}</em></div>${hot.map(row).join('')}`;q('#tv-watch').onclick=e=>{const b=e.target.closest('[data-symbol]');if(b)loadChart(b.dataset.symbol)}};
window.refreshWatchlist=loadPinnedWatch;
addEventListener('DOMContentLoaded',build);
})();
